import { number, z } from "zod";

export const oasCustomerReqDto = z.object({
    name: z.string(),
    owner: z.string(),
    address: z.string(),
    city: z.string(),
    state_id: z.number(),
    country: z.string(),
    pin: z.number(),
    ship_name: z.string(),
    ship_add: z.string(),
    ship_city: z.string(),
    ship_state_id: z.number(),
    ship_country: z.string(),
    ship_pin: z.number(),
    gst_no: z.string(),
    code: z.string(),
    contact_no1: z.string(),
    contact_no2: z.string(),
    desc: z.string(),
    contact_nature_id: z.number(),
    inq_src_id: z.number(),
    industry_id: z.number(),
    machine_id: z.number(),
    consump: z.string(),
    email: z.string(),
    competitor1: z.number(),
    competitor2: z.number(),
    class_ud: z.string(),
    created_by_user_id: z.number(),
    contact_ids: z.array(z.number())
}).openapi({
    description: 'Customer Request Object',
    ref: 'CustomerReqDto',
});

export default interface CustomerReqDto {
    name: string,
    owner: string,
    address: string,
    city: string,
    state_id: number,
    country: string,
    pin: number,
    ship_name: string,
    ship_add: string,
    ship_city: string,
    ship_state_id: number,
    ship_country: string,
    ship_pin: number,
    gst_no: string,
    code: string,
    contact_no1: string,
    contact_no2: string,
    desc: string,
    contact_nature_id: number,
    inq_src_id: number,
    industry_id: number,
    machine_id: number,
    consump: string,
    email: string,
    competitor1: number,
    competitor2: number,
    class_ud: string,
    created_by_user_id: number,
    contact_ids: number[]
}